### ISSUE TITLE
파이썬 서버가 안켜집니다.

### ISSUE THREAD

**Issue by JaeJunday** [42Seoul-Tea42/backend#23]
``` shell
backend     | Traceback (most recent call last):
backend     |   File "/usr/app/srcs/wsgi.py", line 1, in <module>
backend     |     from app import create_app
backend     |   File "/usr/app/srcs/app/__init__.py", line 5, in <module>
backend     |     from .user.userService import register_dummy
backend     |   File "/usr/app/srcs/app/user/userService.py", line 5, in <module>
backend     |     from . import userUtils as utils
backend     |   File "/usr/app/srcs/app/user/userUtils.py", line 1, in <module>
backend     |     from app.smtp import sendSmtpEmail
backend     |   File "/usr/app/srcs/app/smtp.py", line 17, in <module>
backend     |     smtp.login(email_account, email_password)
backend     |   File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
backend     |     (code, resp) = self.auth(
backend     |                    ^^^^^^^^^^
backend     |   File "/usr/local/lib/python3.12/smtplib.py", line 652, in auth
backend     |     authobject(challenge).encode('ascii'), eol='')
backend     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend     | AttributeError: 'NoneType' object has no attribute 'encode'
backend     | unable to load app 0 (mountpoint='') (callable not found or import error)
backend     | *** no app loaded. going in full dynamic mode ***
backend     | *** uWSGI is running in multiple interpreter mode ***
backend     | spawned uWSGI master process (pid: 1)
backend     | spawned uWSGI worker 1 (pid: 6, cores: 2)
backend     | spawned uWSGI worker 2 (pid: 9, cores: 2)
backend     | Python auto-reloader enabled
backend     | spawned uWSGI worker 3 (pid: 11, cores: 2)
backend     | spawned uWSGI worker 4 (pid: 13, cores: 2)
```

# 스웨거를 뽑아보고 싶어서 도커컨테이너를 돌렸는데 파이썬 코드에서 오류가 납니다. 고쳐주세요. @OZestina

**Comment by OZestina** [comment]
.env 파일 내 필요 항목을 주석처리해버린 휴먼 에러로 밝혀졌습니다.
주석 해제하면 정상 작동합니다
